### ISSUE TITLE
install

### ISSUE THREAD

**Issue by fate118** [joselado/qutranpy#1]
how do i install it?i do not linux. how cod i use?

**Comment by joselado** [comment]
Dear fate118,

this software in principle only works in Linux. The easy way to execute it if you have another operating system is that you install a Linux distribution in a virtual machine, and you execute the software inside the virtual machine.

Cheers,
Jose

**Comment by fate118** [comment]
thank you. i should write cd/download/qutranpy/bin    (next)    configure/.        make      make install     but it is wrong

**Comment by joselado** [comment]
Dear fate118

in the main qutranpy folder there is a python script called install, you can execute it as "python install". Afterwards, you can execute the program writing in the terminal "qutranpy". Please note that you need to have installed the Python libraries numpy, scipy and matplotlib.

Cheers,
Jose

**Comment by fate118** [comment]
you can execute it as "python install". 
i install python :
sudo apt-get install python3.6
but qutranpy is different
is it true?

**Comment by joselado** [comment]
Dear fate188,

yes, it is different. To install qutranpy you have to execute the "install" script located in the qutranpy main folder. To execute that script, go to the main folder and execute in the terminal "python install"

Cheers,
Jose

**Comment by fate118** [comment]
i write in terminal python then write
>>> #!/usr/bin/python2.7
... # instalation script
... from __future__ import print_function
>>> import os
>>> # compile fortran files
... os.chdir("pysrc/fortran")
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
FileNotFoundError: [Errno 2] No such file or directory: 'pysrc/fortran'
>>> os.chdir("../../") # return to main folder
>>> path = os.getcwd() # current path
>>> # add this line to the .bashrc
... line = "# Added by QUTRANPY\n"
>>> line += "export PATH=$PATH:"+path+"/bin\n"
>>> line += "export QUTRANPYROOT='"+path+"'\n\n"
>>> print(line)
# Added by QUTRANPY
export PATH=$PATH://bin
export QUTRANPYROOT='/'


>>> fo = open(os.environ["HOME"]+"/.bashrc","a")
>>> fo.write(line)
69
>>> fo.close()
sory is it true?
 i nead fortran  (errore)
.. os.chdir("pysrc/fortran")
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
FileNotFoundError: [Errno 2] No such file or directory: 'pysrc/fortran'

**Comment by joselado** [comment]
Dear fate118,

you do not have to write anything in the python terminal, just write in a shell terminal when you are in the qutranpy folder "python install". That will execute the script "install" located in the qutranpy main folder.

Cheers,
Jose

**Comment by fate118** [comment]
thank you but ihis is errore 
should i install f90?
sana@sana-Inspiron-N5050:~/Downloads/qutranpy-master$  python install
sh: 1: f2py2.7: not found
cp: cannot stat ‘first_neighborsf90.so’: No such file or directory
sh: 1: f2py2.7: not found
cp: cannot stat ‘gauss_inv.so’: No such file or directory
sh: 1: f2py2.7: not found
cp: cannot stat ‘kpmf90.so’: No such file or directory
sh: 1: f2py2.7: not found
cp: cannot stat ‘mean_fieldf90.so’: No such file or directory
# Added by QUTRANPY
export PATH=$PATH:/home/sana/Downloads/qutranpy-master/bin
export QUTRANPYROOT='/home/sana/Downloads/qutranpy-master'



########################################################

You can run the program openning a new terminal and typing
   qutranpy

########################################################

**Comment by fate118** [comment]
when i type qutranpy
this is errore

sana@sana-Inspiron-N5050:~$ qutranpy
Temporal folder is qutranpy_1
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    import matplotlib.pyplot as plt
ImportError: No module named matplotlib.pyplot

**Comment by fate118** [comment]
i have anaconda

**Comment by fate118** [comment]
can you help me please?i need this program

**Comment by joselado** [comment]
Dear fate118,

by default, qutranpy will use the python2.7 that is in your PATH. The best solution is that you install matplotlib, numpy and scipy with "sudo apt-get install", and you use the Python that comes with your system.

Nevertheless, if you wanted to use a different Python, you could edit the file qutranpy/bin/qutranpy and modify the last line

os.system("python2.7 main.py "+pysrc)

For instance, if you want to use the Python from anaconda you should write

os.system("PATH_TO_ANACONDA/bin/python main.py "+pysrc)

where PATH_TO_ANACONDA is the folder where you installed Anaconda

Cheers,
Jose

**Comment by fate118** [comment]
hello
thanks for guid
i download qutranpy  then extract it
i write in terminal cd Downlods/qutrapy-master
then write sudo apt install python
is it true?

**Comment by fate118** [comment]
how to run the program?
